name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Launch Bms Front
      run: npm run dev
    - name: Tests from PW repo
      uses: actions/checkout@v4
      with: 
        repository: padubrulle/bms-automated-tests
        ref: main
        path: tests
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        cd tests
        npm ci
    - name: Install Playwright Browsers
      run: |
        cd tests
        npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        cd tests
        npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
